name = "aether-codex"
main = "worker/index.js"
compatibility_date = "2026-07-01"
[site]
bucket = "./"
exclude = ["node_modules", ".git", ".wrangler", "playwright-report", "test-results", "tests", "*.mjs", "*.sql", "package*.json"]


[vars]
ENVIRONMENT = "development"
MAL_CLIENT_ID = "97959fe7356ea8135f3b19db28cb941f"
MAL_CLIENT_SECRET = "bd43d6c2462b4776d70685b5b4b0fe21c4e2db0b095ac6c3ea4fc215ab4ef7a7"

[[d1_databases]]
binding = "DB"
database_name = "aether_codex_db"
database_id = "707efb23-2b15-4c56-95e3-3aaed94abb93"

# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "aether-codex-files-dev"

[env.preview]
vars = { ENVIRONMENT = "preview", MAL_CLIENT_ID = "97959fe7356ea8135f3b19db28cb941f", MAL_CLIENT_SECRET = "bd43d6c2462b4776d70685b5b4b0fe21c4e2db0b095ac6c3ea4fc215ab4ef7a7" }

[[env.preview.d1_databases]]
binding = "DB"
database_name = "aether_codex_db_preview"
database_id = "707efb23-2b15-4c56-95e3-3aaed94abb93"

# [[env.preview.r2_buckets]]
# binding = "BUCKET"
# bucket_name = "aether-codex-files-preview"

[env.production]
vars = { ENVIRONMENT = "production", MAL_CLIENT_ID = "97959fe7356ea8135f3b19db28cb941f", MAL_CLIENT_SECRET = "bd43d6c2462b4776d70685b5b4b0fe21c4e2db0b095ac6c3ea4fc215ab4ef7a7" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "aether_codex_db"
database_id = "707efb23-2b15-4c56-95e3-3aaed94abb93"

# [[env.production.r2_buckets]]
# binding = "BUCKET"
# bucket_name = "aether-codex-files-prod"


